### PR TITLE
Fixes #234 refer to GPL-2.0 in package.json

### LINKED ISSUE #234: Correct the license in packages.json
The plugin is licensed under the GPL 2.0 so shouldn't the license in the `package.json` use the ID listed in https://spdx.org/licenses/? It just makes people checking their dependencies easier to automatically see where they stand:

https://docs.npmjs.com/files/package.json#license

### PR DESCRIPTION
**Pull request by buckett**
Refer to the GPL2.0 license in the package.json to allow better
automated checking of licenses.

### CODE REVIEW

**Comment by mlewand** [comment]
@buckett Great, thanks for the PR! One minor thing though:

> License under the terms of the GNU General Public License Version 2 or later (the "GPL") (Appendix A).

License is for GPL 2 or later, so we need `GPL-2.0` and `GPL-3.0`. Having that done it's fine.

If I could just ask you to apply this minor fix, we could merge it right off the bat!

**Comment by buckett** [comment]
@mlewand Done.

**Comment by mlewand** [comment]
Amazing! Thank you for a quick turnaround!

**Comment by buckett** [comment]
No problem, thanks for the merge.

**Pull request merged**
